### ISSUE TITLE
Wrong stats

### ISSUE THREAD

**Issue by ShalokShalom** [raid-codex/data#47]
Look at Ring, Amulet and Banner: They dont have speed as possible primary stat, still it is used here: https://raid-codex.com/champions/high-khatun/

Consider checking this at other hero`s as well, maybe some grep through the source.

**Comment by geoffreybauduin** [comment]
You're right. Ring and Amulet cannot have speed. I'll have a look at fixing all the champions as well.

Banner can have speed according to the screenshot from plarium's forum available there: https://raid-codex.com/guides/general-gearing-tips/
